name: Build and test ecli on Ubuntu

on:
  push:
    branches: "*"
    tags:
      - "v*"
    paths:
      - "ecli/**"
      - ".github/**"
  pull_request:
    branches: "*"
    tags:
      - "v*"
    paths:
      - "ecli/**"
      - ".github/**"

env:
  TAG_NAME: ${{ github.ref }}
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2

    - name: get submodule
      run:  git submodule update --init --recursive

    - name: install deps
      run: |
          sudo make -C ecli install-deps

    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies

    - name: make ecli
      run:  make ecli

    - name: run unit tests
      run: |
        cd ecli
        make test

    -name: Upload release asset
        uses: actions/upload-artifact@v2
        with:
          name: ecli-${{ env.TAG_NAME }}
          path: ecli/build/bin/Release/ecli-${{ env.TAG_NAME }}
    -name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          artifacts: ecli-${{ env.TAG_NAME }}

